version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/forecaster-api
hooks:
  BeforeInstall:
    - location: ./beforeInstall.sh
  ApplicationStart:
    - location: ./start.sh
  ApplicationStop:
    - location: ./stop.sh